'use strict';

const { stripHTML, url_for } = require('hexo-util');
const { localGlassCover, prepareGlassCovers } = require('../lib/covers');

function list(collection) {
  if (!collection) return [];
  if (Array.isArray(collection)) return collection;
  return typeof collection.toArray === 'function' ? collection.toArray() : collection.data || [];
}

function publishedPosts(collection) {
  return list(collection)
    .filter(post => post.published !== false)
    .sort((a, b) => Number(b.date) - Number(a.date) || String(a.path).localeCompare(String(b.path)));
}

function plainText(value, length = 180) {
  const text = stripHTML(String(value || '').replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1>/gi, ''))
    .replace(/&nbsp;|&#160;/gi, ' ')
    .replace(/&amp;/gi, '&').replace(/&lt;/gi, '<').replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"').replace(/&#39;|&apos;/gi, "'")
    .replace(/\s+/g, ' ').trim();
  return Array.from(text).slice(0, length).join('');
}

function metadata(post, config) {
  const categories = list(post.categories).map(category => category.name);
  return {
    slug: post.slug,
    title: post.title || '未命名文章',
    date: post.date.format('YYYY-MM-DD'),
    publishedAt: post.date.toISOString(),
    timestamp: Number(post.date),
    cover: typeof post.cover === 'string' ? post.cover : '',
    glassCover: localGlassCover(post.cover, config),
    category: categories[0] || '',
    categories,
    tags: list(post.tags).map(tag => tag.name),
    excerpt: plainText(post.description || post.excerpt || post.content, 480),
    url: url_for.call({ config }, post.path, { relative: false }),
  };
}

hexo.extend.helper.register('welkin_all_posts', function () {
  return publishedPosts(this.site.posts);
});

hexo.extend.helper.register('welkin_metadata', function (post) {
  return metadata(post, this.config);
});

hexo.extend.helper.register('welkin_description', plainText);

hexo.extend.helper.register('welkin_collection', list);

hexo.extend.generator.register('welkin-posts', async function (locals) {
  const posts = publishedPosts(locals.posts).map(post => metadata(post, this.config));
  const prepared = await prepareGlassCovers(posts, {
    config: this.config,
    baseDir: this.base_dir,
    warn: message => this.log.warn(message),
  });
  // A JavaScript data file generated by Hexo: no Python or runtime API is needed on Netlify.
  const json = JSON.stringify(prepared.posts).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
  return [...prepared.routes, { path: 'assets/welkin/posts.js', data: 'window.WELKIN_POSTS = ' + json + ';\n' }];
});

// Hexo's index generator omits the homepage when a new site has no posts.
hexo.extend.generator.register('welkin-empty-pages', function (locals) {
  if (publishedPosts(locals.posts).length) return [];
  const prefix = String(this.config.index_generator?.path || '').replace(/\/?$/, '/').replace(/^\//, '');
  const archives = String(this.config.archive_dir || 'archives').replace(/^\/+|\/+$/g, '');
  return [
    { path: prefix + 'index.html', layout: ['index'], data: { __index: true, current: 1, total: 1, posts: locals.posts } },
    { path: archives + '/index.html', layout: ['archive'], data: { __archive: true, current: 1, total: 1, posts: locals.posts } },
  ];
});
